name: Person-service CI/CD
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Oracle OpenJDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'
          cache: maven

      - name: build project
        run: mvn -B package --file pom.xml

  test:
    name: test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'
          cache: maven

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Run unit-tests
        run: mvn test

  deploy:
    name: Deploy to Render
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger deploy via Render API
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run:
          curl "$deploy_url"

      - name: Sleep for 5 sec
        run: sleep 5s
        shell: bash

      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_Aigr2m1ri3vNCC4KkvpIENDyw9lN
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-ckmmg22216ps73fcjv30
          retries: 20
          wait: 16000
          sleep: 30000

      - name: Run API Tests
        uses: matt-ball/newman-action@v1.0.4
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'