name: Person-service CI/CD
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Oracle OpenJDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'
          cache: maven

      - name: build project
        run: mvn -B package --file pom.xml

  test:
    name: test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'
          cache: maven

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Run unit-tests
        run: mvn test

  deploy:
    name: deploy to render
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger deploy via Render API
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run:
          curl "$deploy_url"